sudo: yes
dist: trusty
before_script:
  - sudo apt-get update -q
  - sudo apt-get install -y texlive-full
  - sudo apt-get install -y pandoc pandoc-data gpp inkscape
  - sudo apt-get install -y asciidoc
  - |
    pushd .
    echo $PATH
    git clone https://gitlab.com/git-latexdiff/git-latexdiff.git
    cd git-latexdiff
    sudo make install
    popd
script:
  - |
    mkdir build
    make
